CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS artists (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mbid      VARCHAR(36)  NOT NULL,
    name      VARCHAR(255) NOT NULL,
    sort_name VARCHAR(255),
    url       VARCHAR(512),
    CONSTRAINT uq_artists_mbid UNIQUE (mbid)
);

CREATE TABLE IF NOT EXISTS favorites (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    artist_id  BIGINT       NOT NULL,
    note       VARCHAR(500),
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_favorites_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_favorites_artist FOREIGN KEY (artist_id) REFERENCES artists(id),
    CONSTRAINT uq_favorites_user_artist UNIQUE (user_id, artist_id)
);
